# Site settings
title: OSS Gate
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 「OSS Gate」は、OSS開発に参加する「入り口」を提供する取り組みです。

  OSS開発に未参加の人を参加する人へ、少し参加したことがある人を継続的に参加する人へ。そうやってOSS開発に参加する人を継続的に増やしていく。それが「OSS Gate」の目的です。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://oss-gate.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  oss-gate

# Build settings
markdown: kramdown
exclude: ["vendor", "Gemfile", "Gemfile.lock"]
